services:
  ecom:
    container_name: ecom
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL}
    image: kgnn-ecom-app:v1.3.2
    user: "101:101"  # Match Nginx user/group
    environment:
      - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL}
    # Comment out ports if using Nginx to serve static files directly
    expose:
      - "4322"  # Expose port 4322 to match astro.config.mjs

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../certs:/etc/nginx/ssl:ro  # Mount cert files into the container
    depends_on:
      - ecom